apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: orders
    app.kubernetes.io/instance: orders-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
  name: orders-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - image: 597088043946.dkr.ecr.ap-south-1.amazonaws.com/orders:latest
          imagePullPolicy: Always
          name: orders
          ports:
            - containerPort: 3001
