apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: orders
    app.kubernetes.io/instance: orders-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: orders
spec:
  selector:
    app: orders
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
